use example1;

create table xyz123(
	fname varchar(10),
    lname varchar(10)
);
insert into xyz123 values ("abc","abc"),("abcdc","xyz"),("abbcdc","mno"),("abcdd","klo");
INSERT INTO XYZ123 VALUES ("XYZC","BAC"),("XYZZ","MNO");
select * from xyz123;
SELECT * FROM XYZ123 WHERE FNAME LIKE "%";
SELECT * FROM XYZ123 WHERE FNAME LIKE "ABC%";
SELECT * FROM XYZ123 WHERE FNAME LIKE "%C";
SELECT * FROM XYZ123 WHERE FNAME LIKE "A___C";


CREATE TABLE X101(
	ROLL INT PRIMARY KEY AUTO_INCREMENT,
    USERNAME VARCHAR(10)
);

CREATE TABLE X102(
	USER_ROLL INT UNIQUE,
    GENDER ENUM("MALE","FEMALE"),
    SALARY INT DEFAULT 0,
    FOREIGN KEY (USER_ROLL) REFERENCES X101(ROLL)
);
INSERT INTO X101 (USERNAME) VALUES ("U1"),("U2");
SELECT * FROM X101;
INSERT INTO X102 VALUES (1,"MALE",10000);
INSERT INTO X102 VALUES (2,"FEMALE",1000);
INSERT INTO X102 VALUES (2,"MALE",1000);
INSERT INTO X102 VALUES (3,"MALE",10000);

CREATE TABLE X201(
	ROLL INT PRIMARY KEY AUTO_INCREMENT,
    USERNAME VARCHAR(10)
);
CREATE TABLE X202(
	USER_ROLL INT,
    GENDER ENUM("MALE","FEMALE"),
    SALARY INT DEFAULT 0,
    FOREIGN KEY (USER_ROLL) REFERENCES X101(ROLL)
);
INSERT INTO X201 (USERNAME) VALUES ("U1"),("U2");
SELECT * FROM X201;
INSERT INTO X202 VALUES (1,"MALE",10000);
INSERT INTO X202 VALUES (2,"FEMALE",1000);
INSERT INTO X202 VALUES (2,"MALE",1000);
INSERT INTO X202 VALUES (3,"MALE",10000);