CREATE DATABASE SCHOOLDB;
USE SCHOOLDB;

CREATE TABLE STUDENTS(
	STUDENT_ID INT PRIMARY KEY AUTO_INCREMENT,
    NAME VARCHAR(100) NOT NULL,
    EMAIL VARCHAR(100) UNIQUE,
    DOB DATE
);

CREATE TABLE TEACHERS(
	TEACHER_ID INT PRIMARY KEY AUTO_INCREMENT,
    NAME VARCHAR(100) NOT NULL,
    SUBJECT VARCHAR(100) NOT NULL,
    EMAIL VARCHAR(100) UNIQUE
);

CREATE TABLE COURSES(
	COURSE_ID INT PRIMARY KEY AUTO_INCREMENT,
    COURSE_NAME VARCHAR(100) NOT NULL,
    TEACHER_ID INT,
    FOREIGN KEY (TEACHER_ID) REFERENCES TEACHERS(TEACHER_ID) ON DELETE SET NULL
);

CREATE TABLE ENROLLMENTS(
	ENROLLMENT_ID INT PRIMARY KEY AUTO_INCREMENT,
    STUDENT_ID INT,
    COURSE_ID INT,
    FOREIGN KEY (STUDENT_ID) REFERENCES STUDENTS(STUDENT_ID) ON DELETE CASCADE,
    FOREIGN KEY (COURSE_ID) REFERENCES COURSES(COURSE_ID) ON DELETE CASCADE
);

CREATE TABLE GRADES(
	GRADE_ID INT PRIMARY KEY AUTO_INCREMENT,
    STUDENT_ID INT,
    COURSE_ID INT,
    GRADE INT CHECK (GRADE BETWEEN 0 AND 100),
    FOREIGN KEY (STUDENT_ID) REFERENCES STUDENTS(STUDENT_ID),
    FOREIGN KEY (COURSE_ID) REFERENCES COURSES(COURSE_ID)
);

INSERT INTO Students (name, email, dob) VALUES
('John Doe', 'john@example.com', '2005-06-15'),
('Emma Smith', 'emma@example.com', '2004-09-10'),
('Liam Brown', 'liam@example.com', '2003-12-05'),
('Sophia Johnson', 'sophia@example.com', '2005-02-20'),
('Michael Davis', 'michael@example.com', '2004-07-30');

INSERT INTO Teachers (name, subject, email) VALUES
('Mr. Williams', 'Mathematics', 'williams@example.com'),
('Ms. Johnson', 'Computer Science', 'johnson@example.com'),
('Dr. Miller', 'Physics', 'miller@example.com');

INSERT INTO Courses (course_name, teacher_id) VALUES
('Mathematics', 1),
('Computer Science', 2),
('Physics', 3);

INSERT INTO Enrollments (student_id, course_id) VALUES
(1, 1), (2, 2), (3, 3), (4, 1), (5, 2);

UPDATE STUDENTS SET EMAIL = "CHANGED@GMAIL.COM" WHERE STUDENT_ID = 1;

DELETE FROM TEACHERS WHERE TEACHER_ID = 3;

TRUNCATE TABLE ENROLLMENTS;

