USE EXAMPLE1;

CREATE TABLE CUSTOMERS(
	CID INT PRIMARY KEY AUTO_INCREMENT,
    CNAME VARCHAR(100),
    CSALARY INT,
    CDEPT VARCHAR(10)
); 

INSERT INTO CUSTOMERS (CNAME,CSALARY,CDEPT) VALUES ("C1",10000,"SF"),("C2",20000,"HW"),("C3",15000,"SW"),("C4",25000,"HW"),("C5",50000,"HR");
SELECT * FROM CUSTOMERS;
SELECT COUNT(*) FROM CUSTOMERS;
SELECT COUNT(*) AS TOTAL_ROWS FROM CUSTOMERS;
SELECT COUNT(CNAME) FROM CUSTOMERS WHERE CSALARY > 20000;
SELECT COUNT(CNAME) AS COUNT FROM CUSTOMERS WHERE CSALARY > 20000;

SELECT SUM(CNAME) FROM CUSTOMERS;
SELECT SUM(CSALARY) FROM CUSTOMERS;
SELECT SUM(CSALARY) AS TOTAL_SALARY FROM CUSTOMERS;

SELECT AVG(CNAME) FROM CUSTOMERS;
SELECT AVG(CSALARY) FROM CUSTOMERS;
SELECT AVG(CSALARY) AS AVG_SALARY FROM CUSTOMERS;

SELECT MIN(CNAME) FROM CUSTOMERS;
SELECT MIN(CSALARY) FROM CUSTOMERS;
SELECT MIN(CSALARY) AS MIN_SALARY FROM CUSTOMERS;

SELECT MAX(CNAME) FROM CUSTOMERS;
SELECT MAX(CSALARY) FROM CUSTOMERS;
SELECT MAX(CSALARY) AS MAX_SALARY FROM CUSTOMERS;

SELECT * FROM CUSTOMERS;
SELECT CDEPT FROM CUSTOMERS GROUP BY CDEPT;
SELECT CDEPT,COUNT(CNAME) FROM CUSTOMERS GROUP BY CDEPT;

SELECT CDEPT,AVG(CSALARY) FROM CUSTOMERS GROUP BY CDEPT;
SELECT CDEPT,AVG(CSALARY) AS AVG_SALRY_DEPT FROM CUSTOMERS GROUP BY CDEPT;
SELECT CDEPT,AVG(CSALARY) FROM CUSTOMERS GROUP BY CDEPT HAVING AVG(CSALARY) > 20000;