CREATE DATABASE EXAMPLE5;

USE EXAMPLE5;

-- INNER JOIN

CREATE TABLE EMPDETAILS(
	EMPID INT PRIMARY KEY,
    EMPNAME VARCHAR(100),
    SALARY INT
);

CREATE TABLE MSTATUS(
	MID INT,
    NAME VARCHAR(100),
    STATUS VARCHAR(100)
);

INSERT INTO EMPDETAILS VALUES (1,"JOHN",40000),(2,"ALEX",25000),(3,"SIMON",43000);

INSERT INTO MSTATUS VALUES (1,"JOHN","MARRIED"),(3,"SIMON","MARRIED"),(4,"STELLA","UNMARRIED");

SELECT * FROM EMPDETAILS;

SELECT * FROM MSTATUS;

SELECT EMPID,NAME, SALARY,STATUS
FROM EMPDETAILS
JOIN MSTATUS
WHERE EMPDETAILS.EMPID = MSTATUS.MID;

SELECT EMPID,NAME, SALARY,STATUS
FROM EMPDETAILS
INNER JOIN MSTATUS
WHERE EMPDETAILS.EMPID = MSTATUS.MID;

SELECT EMPID,NAME, SALARY,STATUS
FROM EMPDETAILS
INNER JOIN MSTATUS
ON EMPDETAILS.EMPID = MSTATUS.MID;

-- LEFT JOIN
SELECT EMPID,EMPNAME, SALARY,STATUS
FROM EMPDETAILS
LEFT JOIN MSTATUS
ON EMPDETAILS.EMPID = MSTATUS.MID;

-- RIGHT JOIN
SELECT EMPID,NAME, SALARY,STATUS
FROM EMPDETAILS
RIGHT JOIN MSTATUS
ON EMPDETAILS.EMPID = MSTATUS.MID;
