USE EXAMPLE1;

CREATE TABLE ABC1(
	C21 TINYTEXT,
    C22 MEDIUMTEXT,
    C23 LONGTEXT
);
INSERT INTO ABC1 VALUES ("QWERTYUIOPOIUYTREWQWERTYUIOPOIUYTREWQWERTYUIOPOIUTRQWERTYUIOPOIUYTREWQWERTYUIOPOIUYTREWQWERTYUIOPOIUTR","QWERTYUIOPOIUYTREWQWERTYUIOPOIUYTREWQWERTYUIOPOIUTRQWERTYUIOPOIUYTREWQWERTYUIOPOIUYTREWQWERTYUIOPOIUTR","QWERTYUIOPOIUYTREWQWERTYUIOPOIUYTREWQWERTYUIOPOIUTRQWERTYUIOPOIUYTREWQWERTYUIOPOIUYTREWQWERTYUIOPOIUTR");

INSERT INTO ABC1 VALUES ("RTYUIOPOIUYTREWQWERTYUIOPOIUTRQWERTYUIOPOIUYTREWQWERTYUIOPOIUYTREWQWERTYUIOPOIUTRRTYUIOPOIUYTREWQWERTYUIOPOIUTRQWERTYUIOPOIUYTREWQWERTYUIOPOIUYTREWQWERTYUIOPOIUTRRTYUIOPOIUYTREWQWERTYUIOPOIUTRQWERTYUIOPOIUYTREWQWERTYUIOPOIUYTREWQWERTYUIOPOIUTRRTYUIOPOIUYTREWQWERTYUIOPOIUTRQWERTYUIOPOIUYTREWQWERTYUIOPOIUYTREWQWERTYUIOPOIUTRRTYUIOPOIUYTREWQWERTYUIOPOIUTRQWERTYUIOPOIUYTREWQWERTYUIOPOIUYTREWQWERTYUIOPOIUTRRTYUIOPOIUYTREWQWERTYUIOPOIUTRQWERTYUIOPOIUYTREWQWERTYUIOPOIUYTREWQWERTYUIOPOIUTRRTYUIOPOIUYTREWQWERTYUIOPOIUTRQWERTYUIOPOIUYTREWQWERTYUIOPOIUYTREWQWERTYUIOPOIUTRRTYUIOPOIUYTREWQWERTYUIOPOIUTRQWERTYUIOPOIUYTREWQWERTYUIOPOIUYTREWQWERTYUIOPOIUTRRTYUIOPOIUYTREWQWERTYUIOPOIUTRQWERTYUIOPOIUYTREWQWERTYUIOPOIUYTREWQWERTYUIOPOIUTRRTYUIOPOIUYTREWQWERTYUIOPOIUTRQWERTYUIOPOIUYTREWQWERTYUIOPOIUYTREWQWERTYUIOPOIUTRRTYUIOPOIUYTREWQWERTYUIOPOIUTRQWERTYUIOPOIUYTREWQWERTYUIOPOIUYTREWQWERTYUIOPOIUTRRTYUIOPOIUYTREWQWERTYUIOPOIUTRQWERTYUIOPOIUYTREWQWERTYUIOPOIUYTREWQWERTYUIOPOIUTRRTYUIOPOIUYTREWQWERTYUIOPOIUTRQWERTYUIOPOIUYTREWQWERTYUIOPOIUYTREWQWERTYUIOPOIUTRRTYUIOPOIUYTREWQWERTYUIOPOIUTRQWERTYUIOPOIUYTREWQWERTYUIOPOIUYTREWQWERTYUIOPOIUTRRTYUIOPOIUYTREWQWERTYUIOPOIUTRQWERTYUIOPOIUYTREWQWERTYUIOPOIUYTREWQWERTYUIOPOIUTRRTYUIOPOIUYTREWQWERTYUIOPOIUTRQWERTYUIOPOIUYTREWQWERTYUIOPOIUYTREWQWERTYUIOPOIUTRRTYUIOPOIUYTREWQWERTYUIOPOIUTRQWERTYUIOPOIUYTREWQWERTYUIOPOIUYTREWQWERTYUIOPOIUTRRTYUIOPOIUYTREWQWERTYUIOPOIUTRQWERTYUIOPOIUYTREWQWERTYUIOPOIUYTREWQWERTYUIOPOIUTRRTYUIOPOIUYTREWQWERTYUIOPOIUTRQWERTYUIOPOIUYTREWQWERTYUIOPOIUYTREWQWERTYUIOPOIUTRRTYUIOPOIUYTREWQWERTYUIOPOIUTRQWERTYUIOPOIUYTREWQWERTYUIOPOIUYTREWQWERTYUIOPOIUTRRTYUIOPOIUYTREWQWERTYUIOPOIUTRQWERTYUIOPOIUYTREWQWERTYUIOPOIUYTREWQWERTYUIOPOIUTRRTYUIOPOIUYTREWQWERTYUIOPOIUTRQWERTYUIOPOIUYTREWQWERTYUIOPOIUYTREWQWERTYUIOPOIUTRRTYUIOPOIUYTREWQWERTYUIOPOIUTRQWERTYUIOPOIUYTREWQWERTYUIOPOIUYTREWQWERTYUIOPOIUTRRTYUIOPOIUYTREWQWERTYUIOPOIUTRQWERTYUIOPOIUYTREWQWERTYUIOPOIUYTREWQWERTYUIOPOIUTRRTYUIOPOIUYTREWQWERTYUIOPOIUTRQWERTYUIOPOIUYTREWQWERTYUIOPOIUYTREWQWERTYUIOPOIUTRRTYUIOPOIUYTREWQWERTYUIOPOIUTRQWERTYUIOPOIUYTREWQWERTYUIOPOIUYTREWQWERTYUIOPOIUTRRTYUIOPOIUYTREWQWERTYUIOPOIUTRQWERTYUIOPOIUYTREWQWERTYUIOPOIUYTREWQWERTYUIOPOIUTRRTYUIOPOIUYTREWQWERTYUIOPOIUTRQWERTYUIOPOIUYTREWQWERTYUIOPOIUYTREWQWERTYUIOPOIUTRRTYUIOPOIUYTREWQWERTYUIOPOIUTRQWERTYUIOPOIUYTREWQWERTYUIOPOIUYTREWQWERTYUIOPOIUTRRTYUIOPOIUYTREWQWERTYUIOPOIUTRQWERTYUIOPOIUYTREWQWERTYUIOPOIUYTREWQWERTYUIOPOIUTRRTYUIOPOIUYTREWQWERTYUIOPOIUTRQWERTYUIOPOIUYTREWQWERTYUIOPOIUYTREWQWERTYUIOPOIUTRRTYUIOPOIUYTREWQWERTYUIOPOIUTRQWERTYUIOPOIUYTREWQWERTYUIOPOIUYTREWQWERTYUIOPOIUTRQWERTYUIOPOIUYTREWQWERTYUIOPOIUYTREWQWERTYUIOPOIUTRQWERTYUIOPOIUYTREWQWERTYUIOPOIUYTREWQWERTYUIOPOIUTR","QWERTYUIOPOIUYTREWQWERTYUIOPOIUYTREWQWERTYUIOPOIUTRQWERTYUIOPOIUYTREWQWERTYUIOPOIUYTREWQWERTYUIOPOIUTR","QWERTYUIOPOIUYTREWQWERTYUIOPOIUYTREWQWERTYUIOPOIUTRQWERTYUIOPOIUYTREWQWERTYUIOPOIUYTREWQWERTYUIOPOIUTR");

INSERT INTO ABC1 VALUES ("QWERTYUIOPOIUYTREWQWERTYUIOPOIUYTREWQWERTYUIOPOIUTRQWERTYUIOPOIUYTREWQWERTYUIOPOIUYTREWQWERTYUIOPOIUTR","QWERTYUIOPOIUYTREWQWERTYUIOPOIUYTREWQWERTYUIOPOIUTRQWERTYUIOPOIUYTREWQWERTYUIOPOIUYTREWQWERTYUIOPOIUTR","QWERTYUIOPOIUYTREWQWERTYUIOPOIUYTREWQWERTYUIOPOIUTRQWERTYUIOPOIUYTREWQWERTYUIOPOIUYTREWQWERTYUIOPOIUTR");

INSERT INTO ABC1 VALUES ("QWERTYUIOPOIUYTREWWERTYUI","QWERTYUIOPOIUYTREWQWERTYUIOPOIUYTREWQWERTYUIOPOIUTRQWERTYUIOPOIUYTREWQWERTYUIOPOIUYTREWQWERTYUIOPOIUTRQWERTYUIOPOIUYTREWQWERTYUIOPOIUYTREWQWERTYUIOPOIUTRQWERTYUIOPOIUYTREWQWERTYUIOPOIUYTREWQWERTYUIOPOIUTRQWERTYUIOPOIUYTREWQWERTYUIOPOIUYTREWQWERTYUIOPOIUTRQWERTYUIOPOIUYTREWQWERTYUIOPOIUYTREWQWERTYUIOPOIUTRQWERTYUIOPOIUYTREWQWERTYUIOPOIUYTREWQWERTYUIOPOIUTRQWERTYUIOPOIUYTREWQWERTYUIOPOIUYTREWQWERTYUIOPOIUTRQWERTYUIOPOIUYTREWQWERTYUIOPOIUYTREWQWERTYUIOPOIUTRQWERTYUIOPOIUYTREWQWERTYUIOPOIUYTREWQWERTYUIOPOIUTRQWERTYUIOPOIUYTREWQWERTYUIOPOIUYTREWQWERTYUIOPOIUTRQWERTYUIOPOIUYTREWQWERTYUIOPOIUYTREWQWERTYUIOPOIUTRQWERTYUIOPOIUYTREWQWERTYUIOPOIUYTREWQWERTYUIOPOIUTRQWERTYUIOPOIUYTREWQWERTYUIOPOIUYTREWQWERTYUIOPOIUTRQWERTYUIOPOIUYTREWQWERTYUIOPOIUYTREWQWERTYUIOPOIUTRQWERTYUIOPOIUYTREWQWERTYUIOPOIUYTREWQWERTYUIOPOIUTRQWERTYUIOPOIUYTREWQWERTYUIOPOIUYTREWQWERTYUIOPOIUTRQWERTYUIOPOIUYTREWQWERTYUIOPOIUYTREWQWERTYUIOPOIUTRQWERTYUIOPOIUYTREWQWERTYUIOPOIUYTREWQWERTYUIOPOIUTRQWERTYUIOPOIUYTREWQWERTYUIOPOIUYTREWQWERTYUIOPOIUTRQWERTYUIOPOIUYTREWQWERTYUIOPOIUYTREWQWERTYUIOPOIUTRQWERTYUIOPOIUYTREWQWERTYUIOPOIUYTREWQWERTYUIOPOIUTRQWERTYUIOPOIUYTREWQWERTYUIOPOIUYTREWQWERTYUIOPOIUTRQWERTYUIOPOIUYTREWQWERTYUIOPOIUYTREWQWERTYUIOPOIUTRQWERTYUIOPOIUYTREWQWERTYUIOPOIUYTREWQWERTYUIOPOIUTRQWERTYUIOPOIUYTREWQWERTYUIOPOIUYTREWQWERTYUIOPOIUTRQWERTYUIOPOIUYTREWQWERTYUIOPOIUYTREWQWERTYUIOPOIUTRQWERTYUIOPOIUYTREWQWERTYUIOPOIUYTREWQWERTYUIOPOIUTRQWERTYUIOPOIUYTREWQWERTYUIOPOIUYTREWQWERTYUIOPOIUTRQWERTYUIOPOIUYTREWQWERTYUIOPOIUYTREWQWERTYUIOPOIUTRQWERTYUIOPOIUYTREWQWERTYUIOPOIUYTREWQWERTYUIOPOIUTRQWERTYUIOPOIUYTREWQWERTYUIOPOIUYTREWQWERTYUIOPOIUTRQWERTYUIOPOIUYTREWQWERTYUIOPOIUYTREWQWERTYUIOPOIUTRQWERTYUIOPOIUYTREWQWERTYUIOPOIUYTREWQWERTYUIOPOIUTR","QWERTYUIOPOIUYTREWQWERTYUIOPOIUYTREWQWERTYUIOPOIUTRQWERTYUIOPOIUYTREWQWERTYUIOPOIUYTREWQWERTYUIOPOIUTR");

CREATE TABLE ABC2(
	C31 ENUM("Male","Female","Others")
);
INSERT INTO ABC2 VALUE ("Male");
INSERT INTO ABC2 VALUE ("MALE");
INSERT INTO ABC2 VALUE ("female");
INSERT INTO ABC2 VALUE ("FEMALE");
INSERT INTO ABC2 VALUE ("oTHERS");
INSERT INTO ABC2 VALUE ("Sai Vardhan");

CREATE TABLE ABC3(
	C41 SET("PLAY","SLEEP","WALK","RUN")
);

INSERT INTO ABC3 VALUES ("SAI VARDHAN");
INSERT INTO ABC3 VALUES ("PLAY");
INSERT INTO ABC3 VALUES ("PLAY,SAI VARDHAN");
INSERT INTO ABC3 VALUES ("PLAY,SLEEP,WALK,RUN");
INSERT INTO ABC3 VALUES ("SLEEP,WALK");

CREATE TABLE EXAMPLE12345(
		C123 ENUM("MALE","FEMALE"),
        C456 SET("WALK","RUN")
);

-- DATE & TIME DATA TYPES

CREATE TABLE XYZ1(
	C1 DATE
);
INSERT INTO XYZ1 VALUES ("2024-08-24");
INSERT INTO XYZ1 VALUES ("24-08-2424");

CREATE TABLE XYZ2(
	C11 TIME
);
INSERT INTO XYZ2 VALUES ("12:12:12");
INSERT INTO XYZ2 VALUES ("120:12:12");
INSERT INTO XYZ2 VALUES ("24:12:12");
INSERT INTO XYZ2 VALUES ("24:59:12");

create table xyz3(
	c22 datetime 
);
insert into xyz3 values ("2024-08-24 12:12:12");
insert into xyz3 values ("2024-08-24");
insert into xyz3 values ("12:12:12");
insert into xyz3 values ("20-2008-24 12:12:12");

CREATE TABLE XYZ4 (
	C33 TIMESTAMP
);
INSERT INTO XYZ4 VALUES ("2024-08-24 12:12:12");

CREATE TABLE USERS(
	ROLL INT,
    FNAME VARCHAR(100),
    LNAME VARCHAR(100),
    GENDER ENUM("MALE","FEMALE"),
    HOBBIES SET("PLAYING","SLEEPING","READING","RUNNING"),
    SIGNUP_DATE DATE,
    SIGNUP_TIME TIME
);
INSERT INTO USERS VALUES (101,"SAI","VARDHAN","MALE","PLAYING,SLEEPING","2024-08-24","12:12:12");
INSERT INTO USERS VALUES ("101","SAI","VARDHAN","MALE","PLAYING,SLEEPING","2024-08-24","12:12:12");
INSERT INTO USERS VALUES ("HELLO","SAI","VARDHAN","MALE","PLAYING,SLEEPING","2024-08-24","12:12:12");

INSERT INTO USERS VALUES (101,"SAI","VARDHAN","MALE","PLAYING,SLEEPING","2024-08-24","12:12:12");


CREATE TABLE USERS1(
	FULL_NAME VARCHAR(100),
    ROLL INT
);
INSERT INTO USERS1 VALUES ("U1",101);
INSERT INTO USERS1 VALUES ("U2",102);
INSERT INTO USERS1 VALUES ("U3",103);

CREATE TABLE CART(
	PNAME VARCHAR(100),
    PPRICE INT,
    ROLL INT
);
INSERT INTO CART VALUES("P1",100,102);
INSERT INTO CART VALUES("P1",100,109);

CREATE TABLE P1(
	C11 INT PRIMARY KEY
);

INSERT INTO P1 VALUES (101);
INSERT INTO P1 VALUES (102);
INSERT INTO P1 VALUES (101);
INSERT INTO P1 VALUES ();










