USE EXAMPLE1;

CREATE TABLE EMPLOYEES(
	ROLL INT PRIMARY KEY AUTO_INCREMENT,
    NAME VARCHAR(100) NOT NULL,
    SALARY INT NOT NULL
);
ALTER TABLE EMPLOYEES ADD COLUMN ADDRESS VARCHAR(10);
	
DESCRIBE EMPLOYEES;

INSERT INTO EMPLOYEES VALUES (101,"N1",10000,"A1");

INSERT INTO EMPLOYEES (ROLL,NAME,SALARY) VALUES (102,"N2",20000);

INSERT INTO EMPLOYEES (SALARY,ROLL,NAME) VALUES (30000,103,"N3");

SELECT * FROM EMPLOYEES; 

INSERT INTO EMPLOYEES VALUES (104,"N5",10000,"A1"),(105,"N6",20000,"A2"),(106,"N7",30000,"A3"); 
 
INSERT INTO EMPLOYEES (ROLL,NAME,SALARY) VALUES (107,"N7",10000),(108,"N8",20000),(109,"N9",30000);

SELECT * FROM EMPLOYEES;

CREATE TABLE EMP1(
	ID INT PRIMARY KEY,
    EMP_NAME VARCHAR(100),
    ADDRESS VARCHAR(100)
);

INSERT INTO EMP1 (ID,EMP_NAME,ADDRESS) 
SELECT ROLL,NAME,ADDRESS FROM EMPLOYEES;

SELECT * FROM EMP1;

SET SQL_SAFE_UPDATES = 0;

UPDATE EMP1 SET EMP_NAME = "SAMPLE";

SELECT * FROM EMP1;

UPDATE EMP1 SET EMP_NAME="SAI VARDHAN" WHERE ID=103;

SELECT * FROM EMP1;

DELETE FROM EMP1;

SELECT * FROM EMP1;

SELECT * FROM EMPLOYEES;

DELETE FROM EMPLOYEES WHERE ROLL = 104;

SELECT * FROM EMPLOYEES;

DELETE FROM EMPLOYEES WHERE ADDRESS IS NULL;

SELECT * FROM EMPLOYEES;
SELECT * FROM EMP1;

SELECT * FROM EMPLOYEES;
TRUNCATE TABLE EMPLOYEES;
SELECT * FROM EMPLOYEES;

SELECT * FROM EMP1;
DROP TABLE EMP1;
SELECT * FROM EMP1;