USE EXAMPLE1;

CREATE TABLE T1(
	C11 INT,
    C22 CHAR(5)
);

CREATE TABLE T2(
	C111 INT,
    C222 VARCHAR(10)
);

INSERT INTO T1 VALUES (101,"C1");
INSERT INTO T1 VALUES (102,"C1");

INSERT INTO T2 VALUES (101,"C11");
INSERT INTO T1 VALUES (102,"C22");
INSERT INTO T1 VALUES (103,"C33");

CREATE TABLE DEPARTMENT(
	DEPT_ID INT PRIMARY KEY,
    DEPT_NAME VARCHAR(15)
);

INSERT INTO DEPARTMENT VALUES (101,"CSE");
INSERT INTO DEPARTMENT VALUES (102,"ECE");

CREATE TABLE STUDENTS(
	ROLL_NO INT PRIMARY KEY,
    NAME VARCHAR(100),
    DEPT INT,
    FOREIGN KEY (DEPT) REFERENCES DEPARTMENT(DEPT_ID)
);
INSERT INTO STUDENTS VALUES (1,"S1",101);
INSERT INTO STUDENTS VALUES (2,"S2",101);
INSERT INTO STUDENTS VALUES (3,"S3",102);
INSERT INTO STUDENTS VALUES (4,"S4",102);
INSERT INTO STUDENTS VALUES (5,"S5",103);

CREATE TABLE T3(
	C123 INT UNIQUE,
    C456 VARCHAR(10) UNIQUE
);

INSERT INTO T3 VALUES (101,"S1");
INSERT INTO T3 VALUES (102,"S2");
INSERT INTO T3 VALUES (NULL,"S3");

CREATE TABLE T4(
	C1 INT NOT NULL,
    C2 VARCHAR(13) NOT NULL
);

INSERT INTO T4 VALUES (101,"S1");
INSERT INTO T4 VALUES (101,"S1");
INSERT INTO T4 VALUES (101,"S1");
INSERT INTO T4 VALUES (NULL,"S1");
INSERT INTO T4 VALUES (101,NULL);

CREATE TABLE T5(
	C11 INT CHECK (C11>=18),
    C12 INT CHECK (C12>=200)
);
INSERT INTO T5 VALUES (18,200);
INSERT INTO T5 VALUES (28,200);
INSERT INTO T5 VALUES (18,400);
INSERT INTO T5 VALUES (15,200);
INSERT INTO T5 VALUES (18,100);

CREATE TABLE T6 (
	C1 INT DEFAULT 10,
    C2 VARCHAR(10) DEFAULT "HELLO",
    C3 INT PRIMARY KEY DEFAULT 10
);

INSERT INTO T6 VALUES (101,"SAI",1);
INSERT INTO T6 VALUES (null,"SAI",2);

CREATE TABLE T7(   
		C1 INT PRIMARY KEY AUTO_INCREMENT
);
INSERT INTO T7 VALUES ();
INSERT INTO T7 VALUES ();
SELECT * FROM T7;
INSERT INTO T7 VALUES (101);
SELECT * FROM T7;
INSERT INTO T7 VALUES ();
SELECT * FROM T7;

CREATE TABLE USERS2(
	USER_ID INT PRIMARY KEY AUTO_INCREMENT,
    USER_NAME VARCHAR(100) NOT NULL,
    USER_AGE INT NOT NULL DEFAULT 0,
    USER_DEPT CHAR(3) NOT NULL,
    USER_SALARY INT CHECK(USER_SALARY>=30000),
    USER_GENDER ENUM("MALE","FEMALE"),
    USER_HOBBIES SET("PLAY","WALK","SLEEP")
);

CREATE TABLE CART1(
	USER_NAME VARCHAR(100) NOT NULL,
    USER_ID INT,
    FOREIGN KEY (USER_ID) REFERENCES USERS2(USER_ID)
);