USE EXAMPLE1;

SELECT * FROM USERS;
DESCRIBE USERS;
SELECT ROLL,CONCAT(FNAME,LNAME) FROM USERS;
SELECT ROLL,CONCAT(FNAME," ",LNAME) AS FULL_NAME FROM USERS;

SELECT * FROM USERS;
SELECT ROLL,CONCAT_WS(" ",ROLL,GENDER,FNAME,LNAME) FROM USERS;
SELECT ROLL,CONCAT_WS(",",ROLL,GENDER,FNAME,LNAME) AS DETAILS FROM USERS;

SELECT * FROM USERS;
INSERT INTO USERS (ROLL,FNAME,LNAME) VALUES (102,"SAI","vardhan");
SELECT * FROM USERS;
SELECT LOWER(FNAME) FROM USERS;
SELECT LNAME FROM USERS;
SELECT UPPER(LNAME) FROM USERS;
SELECT LNAME,FNAME FROM USERS;
SELECT CONCAT(LOWER(FNAME)," ",UPPER(LNAME)) AS FULL_NAME FROM USERS;
SELECT ROLL,FNAME,LNAME FROM USERS WHERE BINARY LNAME = UPPER(LNAME);

SELECT FNAME,LNAME,ROLL FROM USERS;
SELECT FNAME,LENGTH(FNAME) FROM USERS WHERE ROLL = 102;
SELECT FNAME,CHAR_LENGTH(FNAME) AS LEN FROM USERS WHERE ROLL = 102;

SELECT LNAME FROM USERS WHERE ROLL = 102;
SELECT LNAME,SUBSTRING(LNAME,3) FROM USERS WHERE ROLL = 102;
SELECT LNAME,SUBSTRING(LNAME,3,3) FROM USERS WHERE ROLL = 102;

SELECT LNAME FROM USERS WHERE ROLL = 102;
SELECT REVERSE(LNAME) AS REVERED FROM USERS WHERE ROLL = 102;
SELECT UPPER(REVERSE(LNAME)) AS REVERED FROM USERS WHERE ROLL = 102;

SELECT LNAME FROM USERS WHERE ROLL=102;
SELECT REPLACE(LNAME,"han","mn") from users where roll = 102;
SELECT REPLACE(LNAME,"HAN","mn") from users where roll = 102;

SELECT REPLACE("HELLO","LL","K");